# Site settings
title: Aritra Bhakat | Portfolio
description: Portfolio showcasing my talents and projects
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://arrebarritra.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
user_firstname: Aritra
username: Aritra Bhakat
email: arre2barre@gmail.com
github_username:  arrebarritra
linkedin_username:  aritra-bhakat

exclude: ['package.json', 'src' , 'node_modules']
